version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:27017"  
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
