version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    restart: always
    ports:
      - "${PORT}:3000"  
    depends_on:
      - mongodb
    environment:  
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - MONGO_PORT=${MONGO_PORT}

volumes:
  mongodb_data:
